### ISSUE TITLE
Does not work w/ TLD client v2.30 - see pull request

### ISSUE THREAD

**Issue by JesseWV** [Xpazeman/tld-carry-weight-mod#2]
Does not work with TLD 2.30

Please test/merge FrankJeager's [Pull Request](https://github.com/Xpazeman/tld-carry-weight-mod/issues?q=is%3Apr+is%3Aopen+author%3AFrankJeager)

**Comment by Xpazeman** [comment]
This mod was merged into Universal Tweaks
